### ISSUE TITLE
使用Eclipse-Class-Decompiler导出反编译代码时文件编码能不能指定？现在默认方案使用不方便

### ISSUE THREAD

**Issue by walthinking** [cnfree/Eclipse-Class-Decompiler#10]
我是中文Windows 7操作系统，使用Eclipse-Class-Decompiler导出反编译代码，代码中有中文时**默认的字符集编码**是GB2312，一般好像是UTF-8和ANSI(windows)，代码的字符集比较乱，能不能在导出时个性化指定呢——**允许选择常用的或者是系统支持的字符集编码**，例如**UTF-8、GB2312、GBK、ISO8859-1**等？
这时还需要考虑原来编码和指定编码之间的转换，复杂性提高了，在使用时应该更方便些

**Comment by cnfree** [comment]
可以在下一个版本加上指定编码的功能。

不过我本意是尽量简化设置，有些用户已经很反感现在的设置了，其实已经很简洁了。

**Comment by walthinking** [comment]
谢谢cnfree

**Comment by cnfree** [comment]
Fixed it, please update the latest version, thanks.

**Comment by walthinking** [comment]
Thanks!
