### ISSUE TITLE
对maven支持不友好

### ISSUE THREAD

**Issue by anjia0532** [cnfree/Eclipse-Class-Decompiler#14]
maven在无源码的时候会从中央仓库下载javadoc和与源码，但是因为Decompiler成了缺省的class viewer，导致只能通过反编译方式编译源码。是否可以增加开关进行控制？

**Comment by cnfree** [comment]
新版本已经增加了源码的下载。并且增加了对Maven的支持。

如果是Maven项目，默认使用Maven下载。
Gradle会自动下载，无需额外支持。
如果是普通项目，会根据SHA1或者Git地址进行下载代码。

新版本还在代码测试中，近期会发布。

**Comment by anjia0532** [comment]
期待，非常感谢。
