### ISSUE TITLE
该插件和eclipse版本有配套关系吗

### ISSUE THREAD

**Issue by langman** [cnfree/Eclipse-Class-Decompiler#15]
eclipse版本信息：
Eclipse Java EE IDE for Web Developers.

Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

安装插件后，在eclipse中并没有加载。

**Comment by cnfree** [comment]
支持Eclipse 3.6以后的所有版本。

下载了一个Neon.3 Release (4.6.3) Build id: 20170314-1500 测试，没有任何问题。

你试试重新安装一下，看看行不行。

![neon](https://user-images.githubusercontent.com/1320575/27190626-aa520898-5227-11e7-8bfb-9fb9432fef33.png)
