### ISSUE TITLE
'Default Class Decompiler' setting can not be saved

### ISSUE THREAD

**Issue by cypher256** [cnfree/Eclipse-Class-Decompiler#2]
1. Select the FernFlower in preference page , and apply it.
2. Restart the Eclipse.
3. 'Default Class Decompiler' is 'JD-Core'...

It will occur only when selected FernFlower.
In the case of other selection is OK.

**Comment by cnfree** [comment]
Fixed it.

The latest release  2.7.1 contains the fix, please update to 2.7.1, thanks.
