### ISSUE TITLE
eclipse marketplace里找不到这个插件了，问下是什么情况

### ISSUE THREAD

**Issue by bj-wei** [cnfree/Eclipse-Class-Decompiler#29]
RT

**Comment by cnfree** [comment]
我也不知道，好像被Eclipse marketplace下架了，发邮件问还没回复我，不知道什么情况。

**Comment by mioz2077** [comment]
很棒的插件，一直在用。能恢复就更好了，有新进展的话期待通知 😁

**Comment by arathai** [comment]
See here:
https://eclipse.org/org/press-release/20170814_security_bulletin.php
It's about the malicious code that is contained in the plugin when downloaded from the update urls that were given here here until 2 days ago or from the marketplace. The sourcecode in this repository does not contain those classes (at the time of this writing). So either you kept this repository not up-to-date with the version that you're publishing or someone hijacked your webspace and published an altered version.
See also: https://0x10f8.wordpress.com/2017/08/07/reverse-engineering-an-eclipse-plugin/

See also cnfree/Eclipse-Class-Decompiler#30

*edit* OK, just saw you had the updated code here: https://github.com/cpupk/ecd

**Comment by wilburhsu** [comment]
还是找不到这个插件，不能离线安装么？

**Comment by arathai** [comment]
@DeityMon you can get an offline installation which is also ad-free here:
https://github.com/pbi-qfs/ecd/releases
