### ISSUE TITLE
key binding on german keybord

### ISSUE THREAD

**Issue by johnnnnnnnnnnnn** [cnfree/Eclipse-Class-Decompiler#3]
on german keyboard the CTRL+ALT+Q is used to insert the @ so with the keybinding for Procyon decompiler i can't enter the @ (e.g. for annotations)

CTRL+ALT+7, ..8, ..9, ..0 is also used for {[]}

see also https://de.wikipedia.org/wiki/Tastaturbelegung  - T1 (Tastaturbelegung 1):

**Comment by cnfree** [comment]
Fixed it. 

Remove all the key bindings and release new version 2.8.2, please download and update it.
