### ISSUE TITLE
Adware in Marketplace binaries

### ISSUE THREAD

**Issue by iloveeclipse** [cnfree/Eclipse-Class-Decompiler#30]
See https://eclipse.org/org/press-release/20170814_security_bulletin.php

**Comment by cnfree** [comment]
OK, that's my wrong. 

I will remove the codes which can download patch files to Eclipse workspaces.

And the new version won't commit on the eclipse market again.

Some one likes it can still download and install it at github.

**Comment by cnfree** [comment]
Committed a new version 2.10.0, it removed the codes which can download patch files to Eclipse workspaces. 

But it still reserves the decompiler mark links.

https://github.com/cnfree/Eclipse-Class-Decompiler/releases/tag/v2.10.0

**Comment by pbi-qfs** [comment]
What hinders you from removing as well the callbacks to your server and the other webservices from the code? Or at least push your current codebase to this github repo? (The source here dates back to version 2.9.0 from last summer)

**Comment by cnfree** [comment]
The source was committed on the https://github.com/cpupk/ecd. I had removed the codes may harm users. 

These codes never worked on user machine. They were used for patching plugin bugs.

**Comment by RobertZenz** [comment]
So the development of this plugin has been moved to the cpuk repository?

Also, could you please go into details on how the code was supposed to be used and work? I believe that a good way to "restore order" would be neatly explain what that code was doing and how it was working, complete with its intentions.

**Comment by pbi-qfs** [comment]
I created a pull request (https://github.com/cpupk/ecd/pull/1) to the new source repo, which removes the discussed code.

@cnfree: Any worries about merging?

Until the official plug-in is fixed, you can use these patched jar files:
https://github.com/pbi-qfs/ecd/releases/tag/v2.10.0-adFree

**Comment by RobertZenz** [comment]
@iloveeclipse Could you comment on the 0x10F8 post and link to this issue? I believe that would make it easier for many people to figure out what is currently going on (and I don't have a Wordpress account).

**Comment by iloveeclipse** [comment]
@RobertZenz : Done

**Comment by davidmichaelkarr** [comment]
I see that there was just an update for the plugin.  Does this mean the "adware" issue is resolved?

**Comment by pbi-qfs** [comment]
No, the Version 2.10.0_20150815, referenced on "update site 1 and 2" still contain the dubious code. I continue to recommend patching the installation with the jar files from https://github.com/pbi-qfs/ecd/releases/tag/v2.10.0-adFree until the author removed the code in question from his distribution.

**Comment by RobertZenz** [comment]
So, what is the exact state of this?

**Comment by cnfree** [comment]
**Anyone who does not like it, please uninstall this plugin.**
**I will not explain it anymore.**
**I'm not interested in stealing your privacy.**
