### ISSUE TITLE
!! Illegal User Tracking !!

### ISSUE THREAD

**Issue by SkateScout** [cnfree/Eclipse-Class-Decompiler#31]
The code track the user with the Network Interface MAC Adress, an Generated UUID , IP operating system and more. With using the MAC-Address the user is trackable across networks. This is against the law in germany.  Also the code suggest that it is intended to catch advertisement clicks.

{\"user_hash\":\"**-**-**-**-**-**\",
                \"user_uuid\":\"********-****-****-****-************\",
                \"cip\":\"**.**.**.***\",\"country\":\"**\",\"country_code\":\"**\",\"province\":null,\"city\":null,
                \"user_country\":\"US\",\"os_name\":\"**\",\"os_arch\":\"**\",\"os_version\":\"*.*\",
                \"java_version\":\"*\",\"eclipse_product\":\"org.eclipse.epp.package.jee.product\",
                \"eclipse_version\":\"*\",\"decompiler_version\":\"*\",\"decompile_count\":*,
                \"total_decompile_count\":*,\"adclick_count\":*,\"total_adclick_count\":*,\"patch\":\"\",\"fragment\":\"\"}

**Comment by cnfree** [comment]
**Anyone who does not like it, please uninstall this plugin.**
**I will not explain it anymore.**
**I'm not interested in stealing your privacy.**
