### ISSUE TITLE
Inner classes in a class will not decompiled

### ISSUE THREAD

**Issue by markuschen** [cnfree/Eclipse-Class-Decompiler#35]
Hi!

The issue is present in current eclipse release and also before.

Inner classes, i.e. org.mycompany.mainclass$innerclass will not decompile.

I've tried to decompile the innerclass and also the mainclass, in both cases only the mainclass is shown without the content of the inner classes.

Thanks for your hard work.

**Comment by yangshankun** [comment]
what't your ellipse version?

**Comment by RobertZenz** [comment]
Most likely the same as our [#13](https://github.com/ecd-plugin/ecd/issues/13).

TL;DR: Fernflower doesn't show inner classes, switch to a different decompiler.

**Comment by markuschen** [comment]
This was the problem, thanks für that.
