### ISSUE TITLE
请问可否提供本地安装包？天朝网络你懂的

### ISSUE THREAD

**Issue by niss2000** [cnfree/Eclipse-Class-Decompiler#8]
安装好多次了，每次都是read time out，真是服了

**Comment by cnfree** [comment]
Releases下面有离线安装包下载地址

https://github.com/cnfree/Eclipse-Class-Decompiler/releases/download/v2.9.0/eclipse-class-decompiler-update_v2.9.0.zip

**Comment by niss2000** [comment]
太感谢了
